# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYZYbSOHZhQXmloDBwf9q2CPXGWQr60o
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([3,8,1,10])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,1,2,3])
y=np.array([5,7,9,21])
plt.plot(x,y)
plt.show()

matplotlib.pyplot as plt
import numpy as npimport
x=np.array([1,2,2.5,4,5,])
y=np.array([5,3,5,8,9,])
plt.plot(x,y,marker="+")
plt.show()

import matplotlib.pyplot as plt
import numpy as np


x = np.linspace(0, 10, 100)
y1 = np.sin(x)
y2 = np.cos(x)


plt.figure(figsize=(10, 6))


plt.subplot(1, 2, 1)  # (row, column, position)
plt.plot(x, y1, 'r-', label='sin(x)')
plt.title('Sinus Funktsiyasi')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend()


plt.subplot(1, 2, 2)
plt.plot(x, y2, 'b-', label='cos(x)')
plt.title('Kosinus Funktsiyasi')
plt.xlabel('X')
plt.ylabel('Y')
plt.legend()


plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt


t = np.linspace(0, 10, 1000)


heartbeat_signal = np.sin(2 * np.pi * 1 * t) + 0.5 * np.sin(2 * np.pi * 2 * t)


plt.figure(figsize=(10, 6))
plt.plot(t, heartbeat_signal, label="Yurak Urish (EKG)", color="r")


plt.title("Yurak Urishi (EKG) Chizmasi")
plt.xlabel("Vaqt (sekund)")
plt.ylabel("Amplituda")
plt.grid(True)
plt.legend()


plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np


centers = [(0, 0), (2, 2), (-3, -3)]
radii = [1, 2, 0.5]


fig, ax = plt.subplots(figsize=(6, 6))


for (center, radius) in zip(centers, radii):
    circle = plt.Circle(center, radius, edgecolor='b', facecolor='none', linewidth=2)
    ax.add_artist(circle)


ax.set_xlim(-5, 5)
ax.set_ylim(-5, 5)
ax.set_aspect('equal', 'box')


plt.title('Doiralar Chizmasi')
plt.xlabel('X o\'qi')
plt.ylabel('Y o\'qi')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.random.randn(100)
y = np.random.randn(100)

plt.figure(figsize=(8, 6))

plt.scatter(x, y, c='r', marker='o')

plt.title('Dumaloq Nuqtalar Chizmasi')
plt.xlabel('X o\'qi')
plt.ylabel('Y o\'qi')
plt.grid(True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.random.randn(100)


sizes = np.linspace(10, 200, 100)

colors = np.random.rand(100)

plt.figure(figsize=(8, 6))


plt.scatter(x, y, c=colors, s=sizes, alpha=0.6, cmap='viridis')
plt.title('Har xil Rang va Hajmda Dumaloq Nuqtalar')
plt.xlabel('X o\'qi')
plt.ylabel('Y o\'qi')
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(0, 10, 10)
y = np.linspace(0, 10, 10)


sizes = np.arange(1, 11)

colors = np.random.rand(10)

plt.figure(figsize=(8, 6))

plt.scatter(x, y, c=colors, s=sizes**2, alpha=0.6)

plt.title('Dumaloq Nuqtalar: Hajm va Rang')
plt.xlabel('X o\'qi')
plt.ylabel('Y o\'qi')
plt.grid(True)

plt.show()

import matplotlib.pyplot as plt

groups = ['610', '611', '612']
values = [22, 25, 27]

plt.figure(figsize=(8, 6))

plt.bar(groups, values, color=['blue', 'green', 'orange'])


plt.title('Guruhlar va Elementlar Soni')
plt.xlabel('Guruhlar')
plt.ylabel('Elementlar Soni')
plt.grid(True)

plt.show()

import matplotlib.pyplot as plt

groups = ['610', '611', '612']
values = [22, 25, 27]

plt.figure(figsize=(8, 6))

plt.barh(groups, values, color=['blue', 'green', 'orange'])

plt.title('Guruhlar va Elementlar Soni (Gorizontal)')
plt.xlabel('Elementlar Soni')
plt.ylabel('Guruhlar')
plt.grid(True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.array([35,25,25,15])
mylabels=["610","611","612","613"]
plt.pie(y)
plt.show()

import matplotlib.pyplot as plt

groups = ['610', '611', '612']
values = [22, 25, 27]

plt.figure(figsize=(8, 6))

plt.barh(groups, values, color=['blue', 'green', 'orange'])

plt.title('Guruhlar va Elementlar Soni (Gorizontal)')
plt.xlabel('Elementlar Soni')
plt.ylabel('Guruhlar')
plt.grid(True)

plt.show()

import matplotlib.pyplot as plt
import numpy as np

groups = ['610', '611', '612']
values = [22, 25, 27]

center = (0, 0)
radius = 1.5
plt.figure(figsize=(8, 8))

circle = plt.Circle(center, radius, color='lightblue', ec='black', lw=2, fill=True)
plt.gca().add_artist(circle)

for i, (group, value) in enumerate(zip(groups, values)):
    angle = 2 * np.pi * i / len(groups)
    x = center[0] + radius * np.cos(angle)
    y = center[1] + radius * np.sin(angle)

    plt.text(x, y, f'{group}\n{value}', ha='center', va='center', fontsize=12, color='black')

plt.title('Guruhlar va Elementlar Soni (Doira Ichida)', fontsize=14)
plt.xlim(-2, 2)
plt.ylim(-2, 2)
plt.gca().set_aspect('equal', adjustable='box')

plt.axis('off')

plt.show()

import matplotlib.pyplot as plt


groups = ['610', '611', '612']
values = [22, 25, 27]

plt.figure(figsize=(8, 8))


plt.pie(values, labels=groups, autopct='%1.1f%%', startangle=90, colors=['lightblue', 'lightgreen', 'orange'], wedgeprops={'edgecolor': 'black'})


plt.title('Guruhlar va Elementlar Soni (Doiraga Bo\'lib)')


plt.show()